---
title: "Cherwell Weekly Aging Report"
date: "`r format(Sys.time(), '%d %B, %Y')`" 
output: "html_document"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, out.width='90%')
pagebreak <- function() {
  if(knitr::is_latex_output())
    return("\\newpage")
  else
    return('<div style="page-break-before: always;" />')
}
```


```{r File open and setup, include=FALSE}
#
# Library setups
#

library(tidyverse)
library(tidyr)
library(plyr)
library(dplyr)
library(caret)
library(ggplot2)
library(ggthemes)
library(extrafont)
library(scales)
library(stringi)
library(grid)
library(gridExtra)
library(lattice)
library(janitor)
library(rmarkdown)
library(kableExtra)
library(lubridate)
library(stringr)
library(googlesheets)

#--------------------------------------------------------------------
#
# File open, cleanup, and set up for the analysis
#
#--------------------------------------------------------------------

#
# Open the Google Sheet
#

master_file <- gs_title("CAR-info-2019-10-25")
mas_dat     <- gs_read(master_file, skip = 0, header = TRUE, stringsAsFactors = FALSE)

# Open the data file - a Google Sheet in user's top level directory
data_file   <- paste("CAR-input-", as.character(mas_dat[1]))
data_filename <- gs_title(data_file)
dat <- gs_read(data_filename, skip = 1, header = TRUE, stringsAsFactors = FALSE)

# Generate the week ending data from the data file name
Week_Ending <- str_sub(data_filename[2], 11, 20)

# Clean up column / vector names
dat <- rename(dat, replace = c("Incident ID" = "ID",
                               "Created Date Time" = "Created",
                               "Customer Display Name" = "Customer",
                               "Incident Type" = "Type",
                               "Short Description" = "Desc",
                               "Owned By" = "Owner",
                               "SLA Resolve By Deadline" = "Due"))

# Get rid of unneeded column and row information and sort by created date
dat <- dat %>% select(ID, Created, Customer, Type, Desc, Owner, Due)
dat <- dat %>% filter(dat$Created != "")

# Shorten some fields
dat[dat == "Incident"]            <- "Inc"
dat[dat == "Service Request"]     <- "SR"

# Simplify timestamp to simple dates
dat$Created <- sub(' .*', '', dat$Created)
dat$Created <- as.Date(dat$Created, format = "%m/%d/%Y")

dat$Due <- sub(' .*', '', dat$Due)
dat$Due <- as.Date(dat$Due, format = "%m/%d/%Y")

# Add column for days open (Duration)
dat <- dat %>% mutate(Duration = difftime(as.Date(Week_Ending), dat$Created, units = "days"))
dat <- dat %>% arrange(desc(Duration))

# Establish groupings for the open tickets
days_07 <- dat %>% filter(Duration <=  7) %>% select(-Desc)
days_30 <- dat %>% filter(Duration <= 30 & Duration >  7) %>% select(-Desc)
days_60 <- dat %>% filter(Duration <= 60 & Duration > 30) %>% select(-Desc)
over_60 <- dat %>% filter(Duration >  60) %>% select(-Desc)

# Establish groupings for SLA compliance
inc_sla      <- dat %>% filter(Type == "Inc" & Duration <=  2) %>% select(-Desc)
inc_sla_perc <- (nrow(inc_sla) / nrow(dat %>% filter(Type == "Inc"))) * 100
inc_sla_perc <- round(inc_sla_perc, digits = 2)

SR_sla       <- dat %>% filter(Type =="SR" & Duration <= 10) %>% select(-Desc)
SR_sla_perc  <- (nrow(SR_sla) / nrow(dat %>% filter(Type == "SR"))) * 100
SR_sla_perc  <- round(SR_sla_perc, digits = 2)

# Part 1 - ticket sorted by age within owner

owner_durs <- dat %>% arrange(Owner, Duration) %>% select(-Desc)

# Print out tickets by owner
owner_list <- unique(dat$Owner)

for(i in 1:5) {
     cat("Page", i)
     pagebreak()
}


```



**End of Report**
